name: Continuous Deployment
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deployment To Hugging Face
        env:
          HF: ${{ secrets.HF }}
        run: make deploy HF=$HF
        # run: |
        #   echo "$HF_TOKEN" | huggingface-cli login --token
        #   huggingface-cli repo create Drug-Classification --type=spaces --yes || true
        #   git remote add hf https://huggingface.co/namfam/Drug-Classification || true
        #   git push hf main --force